import assert from 'node:assert/strict';import {readFile,mkdir} from 'node:fs/promises';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const data=JSON.parse(await readFile(new URL('../content/learning.json',import.meta.url),'utf8'));const browser=await chromium.launch({executablePath:'/usr/bin/chromium',args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];let count=0;page.on('pageerror',e=>errors.push(e.message));const check=(v,label)=>{assert.ok(v,label);count++;};
try{
 await page.goto(process.env.BASE_URL||'http://127.0.0.1:4174/',{waitUntil:'networkidle'});
 await page.locator('[data-topic-group="repas"]').click();check(await page.locator('.topic-card').count()===4,'food themes filtered');await page.locator('#topic-search').fill('restaurant');check(await page.locator('.topic-card[data-topic="restaurant"]').count()===1,'search within group');await page.locator('#topic-search').fill('zxyz');check(await page.locator('.topic-card').count()===0,'empty search');
 await page.locator('nav [data-view="paths"]').click();check(await page.locator('.path-card').count()===6,'six paths');await page.locator('[data-path="premiers-pas"]').click();check(await page.locator('.path-lessons li').count()===6,'six ordered lessons');await page.locator('.actions [data-path-scene]').click();check((await page.locator('.path-context').textContent()).includes('étape 1 / 6'),'path context');
 const scene=data.scenes.find(s=>s.id==='rencontres');
 async function quiz(correct){await page.locator('[data-quiz="rencontres"]').click();for(let i=0;i<4;i++){const heading=await page.locator('.quiz h2').textContent();const q=scene.phrases.find(p=>heading.includes(p.meaning));const id=correct?q.id:scene.phrases.find(p=>p.id!==q.id).id;await page.locator('[data-answer="'+id+'"]').click();await page.locator('[data-next]').click();}}
 await quiz(true);check((await page.locator('.quiz').textContent()).includes('4 réponses justes sur 4'),'actual score');check(await page.locator('[data-path-scene="famille"]').count()===1,'next path lesson');
 await page.reload({waitUntil:'networkidle'});check(await page.locator('.resume-banner').count()===1,'resume survives reload');check((await page.locator('.resume-banner').textContent()).includes(scene.title),'resume names scene');await page.locator('.resume-banner [data-start]').click();await quiz(false);
 check(await page.evaluate(()=>JSON.parse(localStorage.getItem('darija-enrichment-progress-v1')).scores.rencontres)===4,'worse attempt preserves best score');await page.locator('nav [data-view="paths"]').click();await page.locator('[data-path="premiers-pas"]').click();check((await page.locator('.lesson-status').first().textContent()).includes('4 / 4'),'path displays saved score');
 await mkdir(new URL('../test-output/',import.meta.url),{recursive:true});await page.screenshot({path:new URL('../test-output/path-desktop.png',import.meta.url).pathname,fullPage:true});
 await page.setViewportSize({width:320,height:800});check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'path fits 320');await page.screenshot({path:new URL('../test-output/path-mobile.png',import.meta.url).pathname,fullPage:true});
 await page.locator('nav [data-view="alphabet"]').click();await page.locator('[data-letter="letter-2"]').click();check(await page.locator('[data-speak-letter]').count()===1,'letter-only listening control');await page.keyboard.press('Escape');await page.locator('.object-card[data-word="bab"]').click();check(await page.locator('[data-speak-letter]').count()===0,'no listening control in word');check(!(await page.locator('#dialog-body').textContent()).includes('Audio vérifié à venir'),'no pending word audio');await page.keyboard.press('Escape');
 await page.evaluate(()=>localStorage.setItem('darija-enrichment-progress-v1','{broken'));await page.reload({waitUntil:'networkidle'});check(await page.locator('#notice').isVisible(),'invalid progress explained');await page.locator('.scene-card[data-start="rencontres"]').click();check(await page.evaluate(()=>localStorage.getItem('darija-enrichment-progress-v1'))==='{broken','invalid progress never overwritten');check(errors.length===0,'no exceptions');console.log(count+' path checks passed');
}finally{await browser.close();}
