import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright-core');
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
try{
  const page=await browser.newPage({viewport:{width:390,height:844}});
  const external=[],errors=[];
  const url=(process.env.BASE_URL||'http://127.0.0.1:4173/')+'dist/atelier-autonome.html';
  page.on('request',request=>{if(/^https?:/.test(request.url())&&request.url()!==url)external.push(request.url());});
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(url,{waitUntil:'load'});
  assert.equal(await page.locator('.scene-card').count(),63);
  await page.locator('nav [data-view="alphabet"]').click();
  assert.equal(await page.locator('.letter-card').count(),28);
  await page.locator('[data-word="water"]').click();
  assert.ok((await page.locator('#dialog-body').textContent()).includes('eau'));
  await page.keyboard.press('Escape');
  await page.locator('.brand').click();
  assert.equal(await page.locator('.scene-card').count(),63);
  await page.locator('nav [data-view="dictionary"]').click();
  await page.locator('#word-search').fill('chambre');
  assert.equal(await page.locator('.saved-card').count(),1);
  await page.locator('nav [data-view="scenes"]').click();
  await page.locator('.scene-card[data-start="hotel"]').click();
  await page.locator('[data-build]').click();
  const indexes=await page.locator('[data-pick]').evaluateAll(nodes=>nodes.map(n=>Number(n.dataset.pick)).sort((a,b)=>a-b));
  for(const index of indexes)await page.locator(`[data-pick="${index}"]`).click();
  await page.locator('[data-check-order]').click();
  assert.ok((await page.locator('.feedback').textContent()).includes('bon ordre'));
  await page.locator('nav [data-view="scenes"]').click();
  await page.locator('.topic-card[data-topic="corps"]').click();
  assert.equal(await page.locator('.saved-card').count(),23);
  await page.locator('nav [data-view="scenes"]').click();
  await page.locator('[data-nav="orientation"]').click();
  for(const step of ['forward','right','left'])await page.locator(`[data-move="${step}"]`).click();
  assert.equal(await page.locator('.you-are-here [data-word]').getAttribute('data-word'),'souk');
  assert.equal(await page.locator('[data-route-next]').count(),1);
  await page.locator('nav [data-view="scenes"]').click();
  await page.locator('.topic-card[data-topic="animaux"]').click();
  assert.equal(await page.locator('.saved-card').count(),21);
  assert.equal(await page.locator('.animal-image').count(),6);
  await page.locator('[data-word="mesh"]').click();
  assert.equal(await page.locator('dialog .animal-image').count(),1);
  await page.keyboard.press('Escape');
  await page.locator('nav [data-view="conjugation"]').click();
  assert.equal(await page.locator('[data-conjugation-person]').count(),8);
  await page.locator('[data-conjugation-tense="future"]').click();
  await page.locator('[data-conjugation-negative="true"]').click();
  assert.equal(await page.locator('[data-conjugation-person="ana"]>span').textContent(),'ما غاديش نخدم');
  await page.locator('[data-conjugation-person="ana"]').click();
  assert.equal(await page.locator('.conjugation-chunk.role-negative').count(),2);
  await page.keyboard.press('Escape');
  await page.locator('[data-conjugation-quiz]').click();
  assert.equal(await page.locator('[data-conjugation-answer]').count(),4);
  await page.locator('[data-conjugation-answer]').first().click();
  assert.equal(await page.locator('[data-conjugation-answer]:disabled').count(),4);
  await page.locator('nav [data-view="dictionary"]').click();
  await page.locator('[data-topic="pays"]').click();
  assert.equal(await page.locator('.saved-card').count(),20);
  assert.equal(await page.locator('.country-flag').count(),20);
  assert.ok((await page.locator('.country-flag').first().getAttribute('src')).startsWith('data:image/svg+xml;base64,'));
  await page.locator('.country-flag').first().evaluate(el=>el.decode());
  await page.locator('[data-topic="couleurs"]').click();
  assert.equal(await page.locator('.color-pairs article').count(),6);
  await page.locator('[data-word-quiz="couleurs"]').click();
  assert.equal(await page.locator('[data-word-answer]').count(),4);
  assert.ok((await page.locator('#flag-license').evaluate(el=>el.content.textContent)).includes('Copyright (c) 2013 Panayiotis Lipiridis'));
  await page.locator('nav [data-view="dictionary"]').click();
  await page.locator('[data-topic="mobilier"]').click();
  assert.equal(await page.locator('.saved-card').count(),18);
  assert.equal(await page.locator('.saved-card .furniture-image').count(),6);
  await page.locator('.saved-card[data-word="biro"]').click();
  assert.equal(await page.locator('dialog .furniture-image').count(),1);
  await page.keyboard.press('Escape');
  await page.locator('[data-word-quiz="mobilier"]').click();
  assert.equal(await page.locator('[data-word-answer]').count(),4);
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
  console.log('Standalone HTML verified over HTTP: 63 scenes, 28 letters, word details, dictionary search, sentence builder, themed vocabulary, completed map route, home navigation, future negative conjugation, morphology and exercise, country flags embedded, colour pairs and vocabulary quiz, furniture cards and quiz, no JS error and no secondary network request. Local file navigation is blocked by this cloud browser policy.');
}finally{await browser.close();}
