import React,{useMemo,useState} from "react";import{createRoot}from"react-dom/client";import{Search,BookOpen,Bookmark,ArrowRight,Home,Layers}from"lucide-react";import{entries,scenes,Entry}from"./data";import"./style.css";
const norm=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[’']/g," ").trim();
function App(){const[view,setView]=useState<"home"|"dict"|"scene">("home");const[q,setQ]=useState("");const[selected,setSelected]=useState(scenes[0]);const[saved,setSaved]=useState<string[]>(()=>JSON.parse(localStorage.getItem("darija-saved")||"[]"));
const toggle=(id:string)=>{const n=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(n);localStorage.setItem("darija-saved",JSON.stringify(n))};
const results=useMemo(()=>{let n=norm(q);if(!n)return entries;return entries.filter(e=>[e.fr,e.latin,e.ar,...(e.aliases||[])].some(v=>norm(v).includes(n)))},[q]);
const openScene=(id:string)=>{setSelected(scenes.find(s=>s.id===id)||scenes[0]);setView("scene");scrollTo(0,0)};
const card=(e:Entry)=><article className="word" key={e.id}><button className={"save "+(saved.includes(e.id)?"on":"")} onClick={()=>toggle(e.id)}><Bookmark size={18}/></button><div className="arabic">{e.ar}</div><strong>{e.latin}</strong><span>{e.fr}</span>{e.note&&<small>{e.note}</small>}<button className="context" onClick={()=>openScene(e.scene)}>Voir en situation <ArrowRight size={14}/></button></article>;
return <><header><button className="brand" onClick={()=>setView("home")}><b>د</b><span>darija<br/><small>PAS À PAS</small></span></button><nav><button onClick={()=>setView("home")}><Home/>Accueil</button><button onClick={()=>setView("dict")}><Search/>Dictionnaire</button><button><Bookmark/>À revoir <i>{saved.length}</i></button></nav></header>
<main>{view==="home"&&<><section className="hero"><div><p className="eyebrow">FRANÇAIS → DARIJA MAROCAIN</p><h1>Le darija qui sert<br/><em>dans la vraie vie.</em></h1><p>Voyez le mot. Comprenez-le. Utilisez-le dans une situation réelle. Un parcours conçu pour les francophones qui débutent.</p><div className="actions"><button className="primary" onClick={()=>openScene("meet")}>Commencer <ArrowRight/></button><button className="secondary" onClick={()=>setView("dict")}><Search/>Chercher un mot</button></div></div><div className="heroCard"><span>VOTRE PREMIÈRE EXPRESSION</span><div className="arabic big">سلام</div><h2>salam</h2><p>Bonjour · salut</p><small>Simple, utile, dès votre première conversation.</small></div></section>
<section><div className="sectionTitle"><div><p className="eyebrow">APPRENDRE EN CONTEXTE</p><h2>Qu'allez-vous faire aujourd'hui ?</h2></div><p>Chaque situation vous donne seulement les mots dont vous avez besoin.</p></div><div className="scenes">{scenes.map((s,i)=><button className="scene" onClick={()=>openScene(s.id)} key={s.id}><span className="num">0{i+1}</span><span className="emoji">{s.emoji}</span><div><small>{s.level}</small><h3>{s.title}</h3><p>{s.subtitle}</p><b>{s.words.length} expressions →</b></div></button>)}</div></section>
<section className="dictionaryPromo"><Layers/><div><p className="eyebrow">UN MOT VOUS MANQUE ?</p><h2>Un dictionnaire fait pour apprendre.</h2><p>Cherchez en français, en darija latin ou en arabe, puis retrouvez le mot dans une situation.</p></div><button className="primary" onClick={()=>setView("dict")}>Ouvrir le dictionnaire</button></section></>}
{view==="dict"&&<section className="page"><p className="eyebrow">DICTIONNAIRE D'APPRENTISSAGE</p><h1>Un mot, plusieurs façons de le trouver.</h1><p>Essayez « combien », « chhal », « bshhal » ou « بشحال ».</p><div className="search"><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Français, darija ou arabe…"/><span>{results.length} résultat{results.length!==1?"s":""}</span></div><div className="words">{results.map(card)}</div></section>}
{view==="scene"&&<section className="page"><button className="back" onClick={()=>setView("home")}>← Toutes les situations</button><div className="sceneHead"><span>{selected.emoji}</span><div><p className="eyebrow">{selected.level}</p><h1>{selected.title}</h1><p>{selected.subtitle}</p></div></div><div className="lessonIntro"><BookOpen/><div><b>1 · Les mots utiles</b><p>Commencez par reconnaître ces expressions. Enregistrez celles que vous voulez revoir.</p></div></div><div className="words">{selected.words.map(id=>entries.find(e=>e.id===id)).filter(Boolean).map(e=>card(e!))}</div><div className="coming"><b>Étape suivante</b><h2>Les mots vont devenir une conversation.</h2><p>La V2 est structurée pour ajouter dialogue, compréhension et exercice sans dupliquer le vocabulaire.</p></div></section>}</main><footer><b>د darija · pas à pas</b><span>Voir · comprendre · parler.</span></footer></>};createRoot(document.getElementById("root")!).render(<App/>);