import React,{useMemo,useState}from"react";import{createRoot}from"react-dom/client";import{Search,Bookmark,ArrowRight,Home,BookOpen,Heart,Hash,MessageCircle,Volume2,ChevronLeft}from"lucide-react";import{entries,scenes,Entry}from"./data";import"./style.css";
const norm=(s:string)=>s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[’']/g," ").trim();
type View="home"|"dict"|"scene"|"review"|"tools";
function App(){const[view,setView]=useState<View>("home"),[q,setQ]=useState(""),[selected,setSelected]=useState(scenes[0]),[active,setActive]=useState<Entry|null>(null);const[saved,setSaved]=useState<string[]>(()=>JSON.parse(localStorage.getItem("darija-saved")||"[]"));
const toggle=(id:string)=>{const n=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(n);localStorage.setItem("darija-saved",JSON.stringify(n))};
const results=useMemo(()=>{const n=norm(q);return entries.filter(e=>!n||[e.fr,e.latin,e.ar,...(e.aliases||[])].some(v=>norm(v).includes(n)))},[q]);
const openScene=(id:string)=>{setSelected(scenes.find(s=>s.id===id)||scenes[0]);setView("scene");setActive(null);scrollTo(0,0)};
const word=(e:Entry)=><article className="word" key={e.id} onClick={()=>setActive(e)}><button aria-label="Ajouter aux favoris" className={"save "+(saved.includes(e.id)?"on":"")} onClick={x=>{x.stopPropagation();toggle(e.id)}}><Bookmark size={18}/></button><div className="arabic">{e.ar}</div><strong>{e.latin}</strong><span>{e.fr}</span><div className="tags"><i>Darija</i><i>{scenes.find(s=>s.id===e.scene)?.title||"Vocabulaire"}</i></div><button className="context" onClick={x=>{x.stopPropagation();openScene(e.scene)}}>Voir en situation <ArrowRight size={14}/></button></article>;
const nav=(v:View,label:string,icon:React.ReactNode)=><button className={view===v?"active":""} onClick={()=>setView(v)}>{icon}<span>{label}</span></button>;
return <><header><button className="brand" onClick={()=>setView("home")}><b>د</b><span>darija<small>PAS À PAS</small></span></button><nav>{nav("home","Accueil",<Home/>)}{nav("dict","Dictionnaire",<Search/>)}{nav("tools","Apprendre",<BookOpen/>)}{nav("review","À revoir",<Bookmark/>)}<i className="count">{saved.length}</i></nav></header><main>
{view==="home"&&<><section className="hero"><div><p className="eyebrow">FRANÇAIS → DARIJA MAROCAIN</p><h1>Comprendre.<br/>Parler. <em>Vivre.</em></h1><p>Une méthode complète construite autour des mots et des situations dont vous avez réellement besoin au Maroc.</p><div className="actions"><button className="primary" onClick={()=>openScene("meet")}>Commencer <ArrowRight/></button><button className="secondary" onClick={()=>setView("dict")}><Search/>Dictionnaire</button></div></div><div className="heroCard"><small>EXPRESSION DU JOUR</small><div className="arabic big">بشحال؟</div><h2>bshhal?</h2><p>Combien ça coûte ?</p><div className="pronounce"><Volume2/> Prononciation à valider</div></div></section>
<section className="finder"><Search/><input value={q} onChange={e=>setQ(e.target.value)} onFocus={()=>setView("dict")} placeholder="Chercher : merci, ch7al, بشحال, café…"/></section>
<section><div className="sectionTitle"><div><p className="eyebrow">27 SITUATIONS DU QUOTIDIEN</p><h2>Apprenez là où vous allez parler.</h2></div><p>Chaque situation relie vocabulaire, contexte, conversation et révision.</p></div><div className="scenes">{scenes.map((s,i)=><button className="scene" onClick={()=>openScene(s.id)} key={s.id}><span className="num">{String(i+1).padStart(2,"0")}</span><span className="emoji">{s.emoji}</span><div><small>{s.level}</small><h3>{s.title}</h3><p>{s.subtitle}</p><b>{s.words.length} expressions <ArrowRight size={13}/></b></div></button>)}</div></section></>}
{view==="dict"&&<section className="page"><p className="eyebrow">DICTIONNAIRE FR ↔ DARIJA ↔ العربية</p><h1>Trouvez le mot que vous cherchez.</h1><p>Français, Darija latin, arabe ou variante Arabizi : la recherche accepte plusieurs écritures.</p><div className="search"><Search/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Ex. combien, chhal, bshhal, بشحال…"/><span>{results.length} résultats</span></div><div className="chips">{["bonjour","merci","combien","café","taxi","où","demain"].map(x=><button onClick={()=>setQ(x)}>{x}</button>)}</div><div className="words">{results.map(word)}</div></section>}
{view==="review"&&<section className="page"><p className="eyebrow">VOTRE MÉMOIRE</p><h1>À revoir.</h1><p>Enregistrez les expressions importantes depuis n'importe quelle fiche.</p>{saved.length?<div className="words">{saved.map(id=>entries.find(e=>e.id===id)).filter(Boolean).map(e=>word(e!))}</div>:<div className="empty"><Heart/><h2>Votre carnet est vide.</h2><p>Utilisez le marque-page sur une expression pour la retrouver ici.</p><button className="primary" onClick={()=>setView("dict")}>Explorer le dictionnaire</button></div>}</section>}
{view==="tools"&&<section className="page"><p className="eyebrow">PARCOURS COMPLET</p><h1>Les outils pour vraiment apprendre.</h1><div className="modules"><article><span>أ</span><h2>Lettres & sons</h2><p>Alphabet arabe, sons marocains et repères 3 / 7 / 9.</p><b>Module en construction</b></article><article><Hash/><h2>Les nombres</h2><p>Compter, comprendre un prix, une heure ou un numéro.</p><b>Vocabulaire déjà intégré</b></article><article><MessageCircle/><h2>Dialogues</h2><p>Des conversations courtes construites à partir des 27 situations.</p><b>Prochaine couche pédagogique</b></article><article><Volume2/><h2>Écouter</h2><p>Audio sourcé et exercices d'écoute, sans synthèse présentée comme native.</p><b>Audio à cartographier</b></article></div></section>}
{view==="scene"&&<section className="page"><button className="back" onClick={()=>setView("home")}><ChevronLeft/> Les 27 situations</button><div className="sceneHead"><span>{selected.emoji}</span><div><p className="eyebrow">{selected.level}</p><h1>{selected.title}</h1><p>{selected.subtitle}</p></div></div><div className="lessonSteps"><b>1 · Mots utiles</b><span>2 · Comprendre</span><span>3 · Dialogue</span><span>4 · S'entraîner</span></div><div className="words">{selected.words.map(id=>entries.find(e=>e.id===id)).filter(Boolean).map(e=>word(e!))}</div><div className="lessonNext"><BookOpen/><div><small>OBJECTIF DU MODULE</small><h2>Passer du mot à une conversation réelle.</h2><p>Les dialogues et exercices utiliseront ces mêmes entrées : aucune traduction ne sera dupliquée ailleurs.</p></div></div></section>}
</main>{active&&<div className="overlay" onClick={()=>setActive(null)}><aside className="detail" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setActive(null)}>×</button><small>FICHE D'APPRENTISSAGE</small><div className="arabic huge">{active.ar}</div><h1>{active.latin}</h1><h2>{active.fr}</h2><div className="detailBlock"><b>Prononciation</b><p>{active.latin}</p><button disabled><Volume2/> Audio uniquement après validation</button></div><div className="detailBlock"><b>Contexte</b><p>{scenes.find(s=>s.id===active.scene)?.title}</p><button onClick={()=>openScene(active.scene)}>Apprendre dans la situation →</button></div><button className="favorite" onClick={()=>toggle(active.id)}><Bookmark/> {saved.includes(active.id)?"Retirer des favoris":"Ajouter à mes révisions"}</button></aside></div>}<footer><b>د darija · pas à pas</b><span>Voir · comprendre · parler.</span></footer></>};createRoot(document.getElementById("root")!).render(<App/>);